---
title: "Impact of gamma fitting on Re estimates"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(estimateR)
library(tibble)
library(Metrics)
library(hydroGOF)
library(ggplot2)
```

#Getting original estimates

```{r original estimate, warning=FALSE}
set.seed(2)
shape_incubation = 3.2 
scale_incubation = 1.3
incubation <- list(name="gamma", shape = shape_incubation, scale = scale_incubation)
timesteps <- length(HK_incidence_data$case_incidence)
delay_matrix <- get_matrix_from_empirical_delay_distr(HK_delay_data, timesteps, fit_gamma_distrib = FALSE, ref_date = as.Date("2020-01-18"))
estimation_window = 3
mean_serial_interval = 4.8
std_serial_interval = 2.3
N_bootstrap_replicates <- 100

estimates <- get_block_bootstrapped_estimate(HK_incidence_data$case_incidence,
                                               N_bootstrap_replicates = N_bootstrap_replicates,
                                               smoothing_method = "LOESS",
                                               deconvolution_method = "Richardson-Lucy delay distribution",
                                               estimation_method = "EpiEstim sliding window",
                                               uncertainty_summary_method = "original estimate - CI from bootstrap estimates",
                                               delay_incubation = incubation,
                                               delay_onset_to_report = delay_matrix,
                                               estimation_window = estimation_window,
                                               mean_serial_interval = mean_serial_interval,
                                               std_serial_interval = std_serial_interval,
                                               ref_date = as.Date("2020-01-18"),
                                               time_step = "day"
  )

deconvolved_incidence <- get_infections_from_incidence(incidence_data = HK_incidence_data$case_incidence,
                                delay_incubation = incubation,
                                delay_onset_to_report = delay_matrix,
                                output_infection_incidence_only = FALSE,
                                ref_date = as.Date("2020-01-18")) 
```

#Getting truncated estimates
```{r truncate estimate, warning=FALSE}
set.seed(2)
timesteps_truncated <- length(HK_incidence_data[75:165,]$case_incidence)
delay_matrix_truncated <- get_matrix_from_empirical_delay_distr(HK_delay_data[779:901,], timesteps_truncated, fit_gamma_distrib = FALSE, ref_date = as.Date("2020-04-01"))#only taking the delay data for april-june
estimates_truncated <- get_block_bootstrapped_estimate(HK_incidence_data[75:165,]$case_incidence, #only taking the incidence data for april-june
                                               N_bootstrap_replicates = N_bootstrap_replicates,
                                               smoothing_method = "LOESS",
                                               deconvolution_method = "Richardson-Lucy delay distribution",
                                               estimation_method = "EpiEstim sliding window",
                                               uncertainty_summary_method = "original estimate - CI from bootstrap estimates",
                                               delay_incubation = incubation,
                                               delay_onset_to_report = delay_matrix_truncated,
                                               estimation_window = estimation_window,
                                               mean_serial_interval = mean_serial_interval,
                                               std_serial_interval = std_serial_interval,
                                               ref_date = as.Date("2020-04-01"),
                                               time_step = "day"
  )

deconvolved_incidence_truncated <- get_infections_from_incidence(incidence_data = HK_incidence_data[75:165,]$case_incidence,
                                delay_incubation = incubation,
                                delay_onset_to_report = delay_matrix_truncated,
                                output_infection_incidence_only = FALSE,
                                ref_date = as.Date("2020-04-01")) 
```

```{r plot, echo=FALSE}
 ggplot(dplyr::left_join(estimates, estimates_truncated, by="date"), aes(x = date)) +
    geom_line(aes(y = Re_estimate.x), lwd=  .9, color="red") +
    geom_line(aes(y = Re_estimate.y), lwd=  .9, color="blue") +
    geom_ribbon(aes(x = date, ymax = CI_up.x, ymin = CI_down.x, fill="CI Re"), alpha = 0.15, colour = NA) +
    geom_ribbon(aes(x = date, ymax = CI_up.y, ymin = CI_down.y, fill="CI Re truncated"), alpha = 0.15, colour = NA) +
    scale_fill_manual(values=c("red","blue"), name="fill")+
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    ylab("Reproductive number") +
    coord_cartesian(ylim = c(0, 3.7)) +
    xlab("") +
    theme_bw()

ggplot(dplyr::left_join(deconvolved_incidence, deconvolved_incidence_truncated, by="date"), aes(x = date)) +
    geom_line(aes(y = smoothed_incidence.x), lwd=  .9, color="red") +
    geom_line(aes(y = smoothed_incidence.y), lwd=  .9, color="blue") +
    ylab("Deconvolved incidence") +
    xlab("") +
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    theme_bw()

ggplot(dplyr::left_join(deconvolved_incidence, deconvolved_incidence_truncated, by="date"), aes(x = date)) +
    geom_line(aes(y = deconvolved_incidence.x), lwd=  .9, color="red") +
    geom_line(aes(y = deconvolved_incidence.y), lwd=  .9, color="blue") +
    ylab("Deconvolved incidence") +
    xlab("") +
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    theme_bw()

```
#Testing different smoothing methods

```{r smooth1, warning=FALSE}
set.seed(2)
timesteps_truncated <- length(HK_incidence_data[75:165,]$case_incidence)
delay_matrix_truncated <- get_matrix_from_empirical_delay_distr(HK_delay_data[779:901,], timesteps_truncated, fit_gamma_distrib = TRUE, ref_date = as.Date("2020-04-01"))#only taking the delay data for april-june
estimates_truncated_smooth_test_1 <- get_block_bootstrapped_estimate(HK_incidence_data[75:165,]$case_incidence, #only taking the incidence data for april-june
                                               N_bootstrap_replicates = N_bootstrap_replicates,
                                               smoothing_method = "TEST",
                                               deconvolution_method = "Richardson-Lucy delay distribution",
                                               estimation_method = "EpiEstim sliding window",
                                               uncertainty_summary_method = "original estimate - CI from bootstrap estimates",
                                               delay_incubation = incubation,
                                               delay_onset_to_report = delay_matrix_truncated,
                                               estimation_window = estimation_window,
                                               mean_serial_interval = mean_serial_interval,
                                               std_serial_interval = std_serial_interval,
                                               ref_date = as.Date("2020-04-01"),
                                               time_step = "day"
  )

deconvolved_incidence_smooth_test_1 <- get_infections_from_incidence(incidence_data = HK_incidence_data[75:165,]$case_incidence,
                                delay_incubation = incubation,
                                delay_onset_to_report = delay_matrix_truncated,
                                output_infection_incidence_only = FALSE,
                                ref_date = as.Date("2020-04-01"),
                                smoothing_method = "TEST" ) 
```

```{r plot smooth1, echo=FALSE}
 ggplot(dplyr::left_join(estimates, estimates_truncated_smooth_test_1, by="date"), aes(x = date)) +
    geom_line(aes(y = Re_estimate.x), lwd=  .9, color="red") +
    geom_line(aes(y = Re_estimate.y), lwd=  .9, color="blue") +
    geom_ribbon(aes(x = date, ymax = CI_up.x, ymin = CI_down.x, fill="CI Re"), alpha = 0.15, colour = NA) +
    geom_ribbon(aes(x = date, ymax = CI_up.y, ymin = CI_down.y, fill="CI Re truncated"), alpha = 0.15, colour = NA) +
    scale_fill_manual(values=c("red","blue"), name="fill")+
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    ylab("Reproductive number") +
    coord_cartesian(ylim = c(0, 3.7)) +
    xlab("") +
    theme_bw()

ggplot(dplyr::left_join(deconvolved_incidence, deconvolved_incidence_smooth_test_1, by="date"), aes(x = date)) +
    geom_line(aes(y = smoothed_incidence.x), lwd=  .9, color="red") +
    geom_line(aes(y = smoothed_incidence.y), lwd=  .9, color="blue") +
    ylab("Deconvolved incidence") +
    xlab("") +
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    theme_bw()

ggplot(dplyr::left_join(deconvolved_incidence, deconvolved_incidence_smooth_test_1, by="date"), aes(x = date)) +
    geom_line(aes(y = deconvolved_incidence.x), lwd=  .9, color="red") +
    geom_line(aes(y = deconvolved_incidence.y), lwd=  .9, color="blue") +
    ylab("Deconvolved incidence") +
    xlab("") +
    scale_x_date(date_breaks = "1 month", 
                 date_labels = '%b\n%d') +
    theme_bw()

```

